### ISSUE TITLE
F12报错和公共组件

### ISSUE THREAD

**Issue by leasin** [leasin/lol#1]
1. element组件后台报错，但是不影响页面，报错能不能去掉
2. 3个公共部分能打包一下，配置一下，然后给每个main  vue使用么，现在只能一个一个引用component{ header,footer leftNav}

**Comment by tongpan110** [comment]
这些后台报错有些是组件的可能用法用错了

**Comment by tongpan110** [comment]
因为每个组件需要的都是不一样的  如果配死的话那么其他页面都是有可能会使用到的  尽量是不要配死  如果需要的话就把头部跟底部可以直接挂在主入口进来的地方
